//
// GetMe200ResponseDataSourcesToReconnectInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetMe200ResponseDataSourcesToReconnectInner: Codable, JSONEncodable, Hashable {

    public var id: Double?
    public var email: String?
    public var type: String?

    public init(id: Double? = nil, email: String? = nil, type: String? = nil) {
        self.id = id
        self.email = email
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

