//
// GetMe200ResponseRole.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetMe200ResponseRole: Codable, JSONEncodable, Hashable {

    public var id: Double?
    public var name: String?
    public var permissions: GetMe200ResponseRolePermissions?

    public init(id: Double? = nil, name: String? = nil, permissions: GetMe200ResponseRolePermissions? = nil) {
        self.id = id
        self.name = name
        self.permissions = permissions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case permissions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(permissions, forKey: .permissions)
    }
}

