//
// GetMe200ResponseFlagsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetMe200ResponseFlagsInner: Codable, JSONEncodable, Hashable {

    public var id: Double?
    public var flag: Double
    public var name: String
    public var state: Bool
    public var user: Double?
    public var plan: Double?
    public var creationDate: Date?
    public var modificationDate: Date?

    public init(id: Double? = nil, flag: Double, name: String, state: Bool, user: Double? = nil, plan: Double? = nil, creationDate: Date? = nil, modificationDate: Date? = nil) {
        self.id = id
        self.flag = flag
        self.name = name
        self.state = state
        self.user = user
        self.plan = plan
        self.creationDate = creationDate
        self.modificationDate = modificationDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case flag
        case name
        case state
        case user
        case plan
        case creationDate = "creation_date"
        case modificationDate = "modification_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(flag, forKey: .flag)
        try container.encode(name, forKey: .name)
        try container.encode(state, forKey: .state)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(plan, forKey: .plan)
        try container.encodeIfPresent(creationDate, forKey: .creationDate)
        try container.encodeIfPresent(modificationDate, forKey: .modificationDate)
    }
}

