//
// PostContactsRequestInnerPosition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PostContactsRequestInnerPosition: Codable, JSONEncodable, Hashable {

    public var organisation: String?
    public var role: String?

    public init(organisation: String? = nil, role: String? = nil) {
        self.organisation = organisation
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case organisation
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(organisation, forKey: .organisation)
        try container.encodeIfPresent(role, forKey: .role)
    }
}

